services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "telegramclient"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"