services:
  mysql_telegram_client:
    container_name: mysql_telegram_client
    image: mysql:9.1.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "telegramclient"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_LOG_CONSOLE: "true"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: